name: pwm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - transformers
      - accelerate
      - inseq
      - numpy
      - pandas
      - scikit-learn
      - scipy
      - pyyaml
      - matplotlib
      - pytest
      - pipdeptree
      - python-slugify
      - git+https://github.com/niggoo/LRP-eXplains-Transformers.git
