models:
  - name: Qwen/Qwen3-0.6B
    params:
      max_new_tokens: 5
      do_sample: false

datasets:
  - name: tellmewhy
    path: data/processed/tellmewhy_5_seed42.txt

  - name: wikitext2
    path: data/processed/wikitest2_5_seed42.txt

attribution_functions:
  - name: saliency
    params: {}

  - name: input_x_gradient
    params: {}

  - name: deeplift
    params: {}

  - name: gradient_shap
    params:
      n_samples: 8
      stdevs: 0.01

  - name: value_zeroing
    params: {}


dimensionality_reduction_methods:
  - name: pca
    params:
      n_components: 1

  - name: factor_analysis
    params:
      n_components: 1

  - name: ica
    params:
      n_components: 1

  - name: kernel_pca
    params:
      n_components: 1

  - name: nmf
    params:
      n_components: 1
