models:
  - name: Qwen/Qwen2.5-0.5B-Instruct
    params:
      max_new_tokens: 2
      do_sample: false

datasets:
  - name: tellmewhy
    path: data/processed/tellmewhy_5_seed42.txt


attribution_functions:
  - name: gradient_shap
    params:
      n_samples: 2
      stdevs: 0.01

  - name: value_zeroing
    params: {}

  - name: saliency
    params: {}

  - name: input_x_gradient
    params: {}

  - name: deeplift
    params: {}

dimensionality_reduction_methods:
  - name: pca
    params: { n_components: 5 }

  - name: factoranalysis
    params: { n_components: 5 }

  - name: ica
    params: { n_components: 5 }

  - name: kernelpca
    params: { n_components: 5 }

  - name: nmf
    params: { n_components: 5 }